import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { AuthProvider } from "@/context/authContext";
import { WebSocketProvider } from "@/context/wsContext";
import SnowfallComponent from "@/components/SnowFallComponent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SnowfallComponent />
        <AuthProvider>
          <WebSocketProvider>
            <main>{children}</main>
          </WebSocketProvider>
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
